name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: source/Tours/ToursTests
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: source/Tours/ToursTests
    
  Tests:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Unit Tests
      run: dotnet test --filter FullyQualifiedName~UnitTests
      working-directory: source/Tours/ToursTests
      
    - name: Integration Tests
      run: dotnet test --filter FullyQualifiedName~IntegrationTests
      working-directory: source/Tours/ToursTests
      
    - name: E2E
      run: dotnet test --filter FullyQualifiedName~E2E
      working-directory: source/Tours/ToursTests
