name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: source/Tours/ToursTests
    - name: Build
      run: dotnet build --no-restore
      working-directory: source/Tours/ToursTests
    - name: Unit Tests
      run: dotnet test ToursTests/UnitTests --filter ClassName=ToursTests.UnitTests --no-build --verbosity normal
      working-directory: source/Tours/ToursTests
