name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: source
    - name: Build
      run: dotnet build --no-restore
      working-directory: source
    - name: Unit Tests
      run: dotnet test ToursTests/TestsBL --no-build --verbosity normal
      working-directory: source
    - name: Integration Tests
      run: dotnet test ToursTests/IntegrationTests --no-build --verbosity normal
      working-directory: source
    - name: E2E Tests
      run: dotnet test ToursTests/E2E --no-build --verbosity normal
      working-directory: source
